"""Report generation for Workstream: weekly digest, cost summary, review summary.

Generates Markdown or HTML reports from dashboard data.  Adapted from the
report-generation pattern in rh-ai-quickstart/ai-observability-summarizer.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

logger = logging.getLogger("dashboard.reports")


async def generate_weekly_digest() -> dict[str, str]:
    """Build a weekly digest summarising PRs, Jira, reviews, and AI costs."""
    from config import settings
    from database import (
        get_ai_cost_summary,
        get_jira_stats,
        get_my_prs,
        get_recent_activities,
    )

    prs = await get_my_prs(
        settings.github_username,
        settings.gitlab_username,
        include_closed=True,
    )
    jira = await get_jira_stats()
    activities = await get_recent_activities(limit=200)
    costs = await get_ai_cost_summary("7d")

    open_prs = [p for p in prs if p["state"] in ("open", "draft")]
    merged_prs = [p for p in prs if p["state"] == "merged"]
    ci_failing = [p for p in open_prs if p.get("ci_status") == "failing"]

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        f"# Workstream Weekly Digest — {now}",
        "",
        "## Pull Requests",
        f"- **Open / Draft:** {len(open_prs)}",
        f"- **Merged (lifetime):** {len(merged_prs)}",
        f"- **CI Failing:** {len(ci_failing)}",
    ]
    if open_prs:
        lines.append("")
        lines.append("### Open PRs")
        for pr in open_prs[:10]:
            lines.append(f"- [{pr['title']}]({pr['url']}) — {pr['repo_full_name']}#{pr['number']}")

    lines += [
        "",
        "## Jira",
        f"- **Total tasks:** {jira.get('total', 0)}",
        f"- **In active sprint:** {jira.get('in_sprint', 0)}",
    ]
    for status, count in jira.get("by_status", {}).items():
        lines.append(f"- {status}: {count}")

    totals = costs.get("totals", {})
    lines += [
        "",
        "## AI Usage (Last 7 Days)",
        f"- **API Calls:** {totals.get('total_calls', 0)}",
        f"- **Total Tokens:** {totals.get('total_tokens', 0):,}",
        f"- **Total Cost:** ${totals.get('total_cost', 0):.4f}",
        f"- **Avg Latency:** {totals.get('avg_latency_ms', 0)}ms",
    ]
    by_model = costs.get("by_model", [])
    if by_model:
        lines.append("")
        lines.append("### Cost by Model")
        lines.append("| Model | Calls | Tokens | Cost |")
        lines.append("|-------|-------|--------|------|")
        for m in by_model:
            lines.append(
                f"| {m['model']} | {m['calls']} | "
                f"{m.get('input_tokens', 0) + m.get('output_tokens', 0):,} | "
                f"${m['cost_usd']:.4f} |"
            )

    if activities:
        lines += ["", "## Recent Activity"]
        for a in activities[:15]:
            lines.append(f"- **{a.get('event_type', '')}** by {a.get('actor', '')} on {a.get('pr_title', '')}")

    lines += [
        "",
        "---",
        f"*Generated by Workstream on {now}*",
    ]

    md = "\n".join(lines)
    return {"markdown": md, "html": _md_to_html(md)}


async def generate_cost_report(period: str = "30d") -> dict[str, str]:
    """Build a detailed AI cost report."""
    from database import get_ai_cost_summary

    costs = await get_ai_cost_summary(period)
    totals = costs.get("totals", {})
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        f"# AI Cost Report — {now}",
        f"**Period:** {period}",
        "",
        "## Summary",
        f"- Total API Calls: **{totals.get('total_calls', 0)}**",
        f"- Input Tokens: **{totals.get('total_input_tokens', 0):,}**",
        f"- Output Tokens: **{totals.get('total_output_tokens', 0):,}**",
        f"- Total Cost: **${totals.get('total_cost', 0):.4f}**",
        f"- Average Latency: **{totals.get('avg_latency_ms', 0)}ms**",
    ]

    by_model = costs.get("by_model", [])
    if by_model:
        lines += [
            "",
            "## Breakdown by Model",
            "| Model | Provider | Calls | Input Tokens | Output Tokens | Cost (USD) | Avg Latency |",
            "|-------|----------|-------|-------------|--------------|------------|-------------|",
        ]
        for m in by_model:
            lines.append(
                f"| {m['model']} | {m['provider']} | {m['calls']} | "
                f"{m.get('input_tokens', 0):,} | {m.get('output_tokens', 0):,} | "
                f"${m['cost_usd']:.4f} | {m['avg_latency_ms']}ms |"
            )

    by_feature = costs.get("by_feature", [])
    if by_feature:
        lines += [
            "",
            "## Breakdown by Feature",
            "| Feature | Calls | Tokens | Cost (USD) |",
            "|---------|-------|--------|------------|",
        ]
        for f in by_feature:
            lines.append(f"| {f['feature']} | {f['calls']} | {f.get('tokens', 0):,} | ${f['cost_usd']:.4f} |")

    daily = costs.get("daily", [])
    if daily:
        lines += ["", "## Daily Trend"]
        lines.append("| Date | Calls | Tokens | Cost |")
        lines.append("|------|-------|--------|------|")
        for d in daily[:30]:
            lines.append(f"| {d['day']} | {d['calls']} | {d.get('tokens', 0):,} | ${d['cost_usd']:.4f} |")

    lines += ["", "---", f"*Generated by Workstream on {now}*"]

    md = "\n".join(lines)
    return {"markdown": md, "html": _md_to_html(md)}


async def generate_review_summary() -> dict[str, str]:
    """Build a summary of review intelligence data."""
    from intelligence.db import get_all_reviewer_profiles, get_patterns, get_ri_statistics

    stats = await get_ri_statistics()
    patterns = await get_patterns()
    reviewers = await get_all_reviewer_profiles()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        f"# Review Intelligence Report — {now}",
        "",
        "## Overview",
        f"- PRs Collected: **{stats.get('prs_collected', {}).get('_total', 0)}**",
        f"- Review Comments: **{stats.get('comments', {}).get('total', 0)}**",
        f"- Unique Reviewers: **{len(reviewers)}**",
        f"- Patterns Extracted: **{stats.get('pattern_count', 0)}**",
    ]

    cats = stats.get("comments", {}).get("by_category", {})
    if cats:
        lines += ["", "## Comment Categories"]
        for cat, cnt in sorted(cats.items(), key=lambda x: -x[1]):
            lines.append(f"- **{cat}:** {cnt}")

    if reviewers:
        lines += [
            "",
            "## Top Reviewers",
            "| Reviewer | Reviews | Comments | Avg/PR | Focus Areas |",
            "|----------|---------|----------|--------|-------------|",
        ]
        for r in reviewers[:10]:
            focus = ", ".join(r.get("focus_areas", [])[:3]) if isinstance(r.get("focus_areas"), list) else ""
            lines.append(
                f"| {r['reviewer']} | {r.get('total_reviews', 0)} | "
                f"{r.get('total_comments', 0)} | "
                f"{r.get('avg_comments_per_pr', 0):.1f} | {focus} |"
            )

    if patterns:
        lines += ["", "## Top Patterns"]
        for p in patterns[:15]:
            lines.append(f"- **[{p.get('category', '')}]** {p.get('pattern', '')} *(freq: {p.get('frequency', 0)})*")

    lines += ["", "---", f"*Generated by Workstream on {now}*"]

    md = "\n".join(lines)
    return {"markdown": md, "html": _md_to_html(md)}


def _md_to_html(md: str) -> str:
    """Minimal Markdown-to-HTML for reports (no external deps)."""

    html_lines = []
    in_table = False

    for line in md.split("\n"):
        stripped = line.strip()

        if stripped.startswith("# "):
            html_lines.append(f"<h1>{_esc(stripped[2:])}</h1>")
        elif stripped.startswith("## "):
            html_lines.append(f"<h2>{_esc(stripped[3:])}</h2>")
        elif stripped.startswith("### "):
            html_lines.append(f"<h3>{_esc(stripped[4:])}</h3>")
        elif stripped.startswith("| ") and "---" in stripped:
            continue
        elif stripped.startswith("| "):
            if not in_table:
                html_lines.append("<table>")
                in_table = True
            cells = [c.strip() for c in stripped.split("|")[1:-1]]
            tag = (
                "th"
                if not any("<td>" in l for l in html_lines[-3:] if "<t" in l) and html_lines[-1] == "<table>"
                else "td"
            )
            html_lines.append("<tr>" + "".join(f"<{tag}>{_inline(c)}</{tag}>" for c in cells) + "</tr>")
        elif stripped.startswith("- "):
            if in_table:
                html_lines.append("</table>")
                in_table = False
            html_lines.append(f"<li>{_inline(stripped[2:])}</li>")
        elif stripped == "---":
            if in_table:
                html_lines.append("</table>")
                in_table = False
            html_lines.append("<hr>")
        elif stripped.startswith("*") and stripped.endswith("*"):
            html_lines.append(f"<p><em>{_esc(stripped.strip('*'))}</em></p>")
        elif stripped:
            if in_table:
                html_lines.append("</table>")
                in_table = False
            html_lines.append(f"<p>{_inline(stripped)}</p>")
        else:
            if in_table:
                html_lines.append("</table>")
                in_table = False

    if in_table:
        html_lines.append("</table>")

    body = "\n".join(html_lines)
    return (
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        "<style>"
        "body{font-family:Inter,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#333;line-height:1.6}"
        "h1{border-bottom:2px solid #6c5ce7;padding-bottom:8px}"
        "h2{color:#6c5ce7;margin-top:24px}"
        "table{border-collapse:collapse;width:100%;margin:12px 0}"
        "th,td{border:1px solid #ddd;padding:6px 10px;text-align:left;font-size:13px}"
        "th{background:#f8f8f8;font-weight:600}"
        "li{margin:4px 0}"
        "code{background:#f0f0f0;padding:2px 4px;border-radius:3px;font-size:12px}"
        "hr{border:none;border-top:1px solid #eee;margin:24px 0}"
        "</style></head><body>\n" + body + "\n</body></html>"
    )


def _esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _inline(text: str) -> str:
    import re

    text = _esc(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    text = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', text)
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    return text
