apiVersion: v1
kind: Service
metadata:
  name: workstream
  labels:
    app: workstream
spec:
  selector:
    app: workstream
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
